### PR TITLE
Apply python black formatting

### PR DESCRIPTION
**Pull request by sponcebus**
Apply [python black](https://github.com/psf/black) to make codebase more readable. There are no functional changes in this PR, it's only running `black .` in the root directory.

### CODE REVIEW

**Comment by mfish33** [comment]
Is there a reason to use black over pylint? @Strip3s if we use pylint it can easily be added to the CI pipline in order to enforce style on every commit.

**Comment by sponcebus** [comment]
Presumably black can also be added to the CI. It's down to preference, but I think black is generally the more popular / favored between the two.

**Comment by Strip3s** [comment]
I would like the team's feedback on this regarding which one is more preferred. I rarely use python so I'll default to what the team's preference would be.

**Review by jack60612 — CHANGES_REQUESTED** [review]
If it ain't broke don't fix it lol

**Pull request closed without merging**
