### PR TITLE
Add the possibility to select Canada as a country

### PR DESCRIPTION
**Pull request by kuchosauronad0**
Nice work on this fork so far.  I thought it would be nice to add the ability to change the country. Actually implementing other shops will probably take much more time than this but I will try my best. Let me know what you think.

Cheers

### CODE REVIEW

**Comment by gr33k** [comment]
Anyone tested this with a Canada order to see if it works? If so - I'm all for adding love for our Canadian folks 👍

**Review by gr33k — APPROVED** [review]
Be nice to see a few Canadian customers put this through the ranks. Looks good to start!

**Review by Strip3s — APPROVED** [review]

**Comment by Strip3s** [comment]
Thanks for the contribution looks great!

**Comment by kuchosauronad0** [comment]
> Anyone tested this with a Canada order to see if it works? If so - I'm all for adding love for our Canadian folks +1

I actually tried to test it but: the bot will err out both sites due to things unrelated to this PR AND when checking the websites I realized that they don't have an option to select another country at all.. So ¯\_(ツ)_/¯ My plan is to try to get some smaller retailers to work in the hopes that the bot protection there is more relaxed

**Pull request merged**
